export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const PROFILE_REQUESTED = 'PROFILE_REQUESTED';
export const PROFILE_SUCCEEDED = 'PROFILE_SUCCEEDED';
export const PROFILE_FAILED = 'PROFILE_FAILED';

export const TOGGLE_MODAL_REQUESTED = 'TOGGLE_MODAL_REQUESTED';
export const TOGGLE_MODAL_SUCCEEDED = 'TOGGLE_MODAL_SUCCEEDED';
